# Iron Dome for Mosquitoes Configuration
# Advanced AI-powered pest detection system

# Detection Settings
detection:
  model_path: "models/yolov8n.pt"
  confidence_threshold: 0.3
  iou_threshold: 0.5
  classes_to_detect: ["mosquito", "insect", "fly"]
  max_detections: 10
  detection_timeout: 30

# Camera Settings
camera:
  phone_link:
    enabled: true
    capture_folder: "data/captures"
    auto_capture: false
    capture_interval: 5
  resolution:
    width: 1920
    height: 1080
  quality: 85

# System Settings
system:
  log_level: "INFO"
  log_file: "logs/system.log"
  max_log_size: "10 MB"
  backup_enabled: true
  auto_cleanup: true
  cleanup_interval: 24  # hours

# Database Settings
database:
  type: "sqlite"
  path: "data/system.db"
  auto_backup: true
  backup_interval: 7  # days

# Monitoring Settings
monitoring:
  enabled: true
  metrics_interval: 60  # seconds
  alert_threshold: 0.8
  performance_tracking: true

# Prevention Settings
prevention:
  enabled: true
  methods:
    - "ultrasonic"
    - "light_trap"
    - "chemical_barrier"
  auto_activation: false

# Web Interface Settings
web:
  enabled: true
  host: "localhost"
  port: 5000
  debug: false
  ssl_enabled: false

# Performance Settings
performance:
  max_memory_usage: "2 GB"
  cpu_limit: 80  # percentage
  gpu_acceleration: true
  batch_processing: true
  cache_enabled: true 